### ISSUE TITLE
Y/Nの文字が見切れている

### ISSUE THREAD

**Issue by namecoco256** [namecoco256/yokosuka-sound#21]
その影響でボタンも若干中央からずれている
![1A37BEFC-982E-4686-8C2D-7591A3314117](https://user-images.githubusercontent.com/74481445/124603158-98883c00-dea4-11eb-9eca-c3bf9fecf733.jpeg)
![Uploading 68DD015D-CE90-4F75-A6F9-6E559E1AE658.png…]()

**Comment by ray-chan-dayo** [comment]
ビジュアル面の変更で解決
